### ISSUE TITLE
Add completion for Sass/SCSS

### ISSUE THREAD

**Issue by jsit** [othree/csscomplete.vim#11]
Since so many people's personal configs (and for instance Tim Pope's vim-haml) set `csscomplete#CompleteCSS` as the `omnifunc` for sass/scss files, I think it might make sense to include a bunch of Sass/SCSS stuff in this completion file. For instance `@mixin`, `@include`, as well as functions like `unquote()` etc. -- rather than creating a new plugin with a `scsscomplete#CompleteSCSS` function that almost nobody would be set up for.

**Comment by jsit** [comment]
For instance, this commit would get us part way there:

jsit/csscomplete.vim@7be51c2a

**Comment by othree** [comment]
Thanks for suggestion.
I don't think its good idea to add scss stuff to css files.
But I think its ok to have some way to let user can extend it.
Maybe setting a global variable.
I will do some research to see if there were other script doing this.

**Comment by jsit** [comment]
Yeah I kinda wondered about that too, like I wish I could write a sass completion function that would inherit all of csscomplete.vim and then just add stuff.

**Comment by jsit** [comment]
I've set up a separate sasscomplete.vim repo: https://github.com/jsit/sasscomplete.vim
