### ISSUE TITLE
mv data/ dict/

### ISSUE THREAD

**Issue by xmlscript** [othree/csscomplete.vim#2]
请考虑将data目录更名为dict。

**Comment by othree** [comment]
Any reason?

**Comment by xmlscript** [comment]
那个目录底下的文件其实就是dict，完全可以用 set dict+=dict/*.txt 来引入，当然dict这个英文的意思有很多理解，在这个场景下，data不具代表性，dict更贴合。

上述都是扯淡，其实真是原因是：我之前已经使用了dict这个目录名，所以都叫同一个名字，不会让目录看起来七零八落的。
