### ISSUE TITLE
Wrong css/scss url() completion

### ISSUE THREAD

**Issue by eugen0329** [othree/csscomplete.vim#4]
According to w3: 
Partial URLs are interpreted relative to the source of the style sheet, not relative to the document.

Source: https://www.w3.org/TR/REC-CSS1/#url

So if I have a css file in css/ and images in img/, proper completion result must be:
background-image: url(../img/bg.png);

Here is Shougo's (neocomplete/deoplete completion frameworks author) responce:
Shougo/neoinclude.vim#13

**Comment by othree** [comment]
I don't think csscomplete did this part.
The only related part in the code is for:

``` css
@import url(
```

Do you use any other tool to help complete file names?

**Comment by othree** [comment]
If you use autocomplpop.vim or any other vim script triggers `<C-x><C-f>`
You could try the option `autochdir`

**Comment by othree** [comment]
A simple doc https://github.com/othree/til/blob/master/vim/filename-complete.md
