### ISSUE TITLE
Feature request: customizable postfix

### ISSUE THREAD

**Issue by af** [othree/csscomplete.vim#7]
Hi, thanks for this plugin! It's really nice to have all of the latest css features available in autocomplete.

I write a lot of stylus, where generally there isn't a trailing semicolon on the rules. By default this completion function adds them, so I keep going back to delete them after, which is a minor inconvenience. 

Simply changing line 120 to `let postfix = ""` makes this work perfectly for me, so would it be possible to read a global config var (eg `let g:csscomplete_postfix = ""`), and if it's set, use that for the postfix instead of `";"`?

**Comment by othree** [comment]
I think I will add a filetype detection and this.

**Comment by othree** [comment]
Please try latest reversion.

I add filetype detection and `g:csscomplete_postfix`, `b:csscomplete_postfix` support.

`b:csscomplete_postfix` should work with `autocmd` (but not yet tested).

**Comment by af** [comment]
Works great, thank you!
